logging:
  level:
    cn.ddossec: debug # 日志级别

server:
  port: 5000 # 端口号

spring:
  application:
    name: consumption-user # 服务名称

  cloud:
    nacos:
      discovery:
        server-addr: localhost:80 #nacos服务的地址 不要加http
    sentinel:
#      transport:
#        dashboard: localhost:8080
#      eager: true
#      datasource:
#        ds:
#          nacos:
#            server-addr: localhost:8849
#            group-id: DEFAULT_GROUP
#            rule-type: flow
#            data-id: my-goods-sentinel
#            data-type: json

ribbon:
  eager-load:
    enabled: true
    clients: provide-goods  #多个服务使用逗号隔开

feign:
  sentinel:
    enabled: true

ahas:
  namespace: default
  license: 26be22becb704f2d86096e6c3bcd878c
project:
  name: consumer-user

